### PR TITLE
Respect symlinks in url_stat

### PR DESCRIPTION
**Pull request by DanielSiepmann**
url_stat is called with an additional $flags argument by PHP.
This includes an flag whether info about sylimk or symlink target should
be returned.

Prior to this change, stat was used all the time, delivering results for
the target of symlinks.
Respecting the flag, lstat is used to return info about the symlink
instead, when requested.

This will properly return infos for is_link() calls.

### CODE REVIEW

**Comment by sanmai** [comment]
Looks sensible to me. Do you think you can manage to make a test?

**Comment by DanielSiepmann** [comment]
Pushed an update with added test.

**Comment by DanielSiepmann** [comment]
This should resolve https://github.com/infection/infection/issues/778

**Comment by DanielSiepmann** [comment]
I don't understand the issue psalm reports. It looks like it is not related to the change. Poorly I'm not able to fix it as I don't understand it. Maybe you have some hint @sanmai?

**Comment by sanmai** [comment]
I'm going to push another PR to fix this Psalm issue, give me a sec.

**Comment by DanielSiepmann** [comment]
Thanks, so once https://github.com/infection/include-interceptor/pull/15 is merged, this PR can be rebased and should be fine :+1:

**Comment by maks-rafalko** [comment]
#15 has been merged to master and to this branch, now it's green.

I'm going to merge it to master, do a release and update `infection/infection`.

Thank you @DanielSiepmann and @sanmai for your help!

**Pull request merged**
